# Generated by Django 4.1.3 on 2024-03-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cosine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                ("jobid", models.AutoField(primary_key=True, serialize=False)),
                ("jobtitle", models.CharField(max_length=100)),
                ("jobfile", models.FileField(upload_to="job_files/")),
                (
                    "hr_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cosine.hrinfo"
                    ),
                ),
            ],
        ),
    ]
