# Generated by Django 4.1.3 on 2024-03-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosine", "0002_jobdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdetails",
            name="jobfile",
            field=models.FileField(upload_to="jobfile/"),
        ),
    ]
